### ISSUE TITLE
File <X> appears to be an elf binary

### ISSUE THREAD

**Issue by whitedavidp** [openpst/readmbn#2]
Hello and thanks for this. I seem to have built properly but when trying to read a .mbn file from my phone I get this error. I can see inside the file in question that it is indeed and ELF but thought that is what these are supposed to me. I look at the files in the test folder but they are certainly not ELF files. Perhaps there are multiple forms of .mbn files? Thanks

**Comment by ghassani** [comment]
There is an older version of mbn before code signing. However, some firmware packages distribute mbn extension files but they are just elf binaries. Not really sure why they end up with an mbn (i have even seen .bin) extensions, if it is an OEM thing or something part of the QC SoC build process. Typically, now adays parts of the firmware like sbl1, tz, etc are just elf binaries.

This program just checks the first DWORD of the file and if it is equal to ELF header magic it just stops and reports that message.
